### ISSUE TITLE
infografia_alvaro froylan pacheco osorio

### ISSUE THREAD

**Issue by Alvaro2-0** [SistemasTecTlaxiaco/actividad-1-infografia-Alvaro2-0#2]
[infografia vida-alvaro Froylan Pacheco Osorio.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Alvaro2-0/files/12581116/infografia.vida-alvaro.Froylan.Pacheco.Osorio.pdf)

**Comment by Julissamigdalia** [comment]
Buen trabajo, faltaron referencias bibliográficas

**Comment by Julissamigdalia** [comment]
Buen trabajo, faltaron referencias bibliográficas
Calificación:18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
